# Generated by Django 5.1.2 on 2024-11-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='No message provided.', max_length=600),
        ),
    ]
